# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Debug secrets
      run: |
        echo "EMAIL length: ${#EMAIL}"
        echo "EMAIL2 length: ${#EMAIL2}"
        echo "EMAIL_PASSWORD length: ${#EMAIL_PASSWORD}"
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL2: ${{ secrets.EMAIL2 }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    - name: Run Python script
      env:
        PHONE: ${{ secrets.PHONE }}
        SMS_API_KEY: ${{ secrets.SMS_API_KEY }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL2: ${{ secrets.EMAIL2 }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }})
      run: python main.py --tl 18



        
